spring.application.name=order-service

server.port=8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.circuitbreaker.instances.item.allow-health-indicator-to-fail=true
resilience4j.circuitbreaker.instances.item.sliding-window-type=count-based
resilience4j.circuitbreaker.instances.item.sliding-window-size=10
resilience4j.circuitbreaker.instances.item.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.item.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.item.permitted-number-of-calls-in-half-open-state=3

management.endpoints.web.exposure.include=health,circuitbreakers

eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true